[package]
name = "saddle-systems-game-feel-example-platformer"
version = "0.1.0"
edition = "2024"
publish = false

[features]
e2e = ["dep:saddle-bevy-e2e"]

[dependencies]
bevy = { workspace = true }
saddle-systems-game-feel = { workspace = true }
saddle-systems-game-feel-example-support = { path = "../support" }
saddle-pane = { git = "https://github.com/julien-blanchon/saddle-pane" }
saddle-bevy-e2e = { workspace = true, optional = true }

[lints]
workspace = true
